# Required
version: 2

# Sphinx configuration file.
sphinx:
  configuration: docs/conf.py

# Image to use
build:
  image: testing
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
    
# Configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      
# # Enable pdf docs generation
# formats:
#   - pdf
