# Required
version: 2

# Image to use
build:
  image: testing

# Configuration
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      
# Enable pdf docs generation
sphinx:
  fail_on_warning: true

formats:
  - pdf
