[tool.poetry]
name = "resomapper"
version = "1.0.0"
description = "Pipeline for processing MR images and generating parametric maps."
authors = ["Biomedical-MR"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "resomapper" }
]

[tool.poetry.dependencies]
python = "^3.10"
brkraw = "0.3.11"
dipy = "1.8.0"
simpleitk = "2.4.1"
pydicom = "3.0.1"
numpy = "1.26.4"
opencv-python = "4.11.0.86"
nibabel = "5.3.2"
matplotlib = "^3.10.7"
colorama = "^0.4.6"
seaborn = "^0.13.2"
tqdm = "^4.67.1"
scikit-image = "0.25.2"
scikit-learn = "1.6.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
resomapper_cli = "resomapper.cli:run_cli"
resomapper_auto = "resomapper.auto:run_auto"